// Package main provides extract command functionality for amorphctl
package main

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/solifugus/amorphdb/internal/protocol"
)

// ExtractCommand handles data extraction operations
type ExtractCommand struct {
	client *ControlClient
}

// NewExtractCommand creates a new extract command handler
func NewExtractCommand(client *ControlClient) *ExtractCommand {
	return &ExtractCommand{client: client}
}

// ExtractSubtree extracts a subtree and generates MBL script
func (ec *ExtractCommand) ExtractSubtree(pathStr string, outputFile string) error {
	// Parse path string into components
	path := strings.Split(pathStr, ".")
	if len(path) == 1 && path[0] == "" {
		path = []string{} // Root path
	}

	// Validate path components
	if err := ec.validatePath(path); err != nil {
		return fmt.Errorf("invalid path: %w", err)
	}

	fmt.Printf("Extracting subtree at '%s'...\n", pathStr)

	// Create extract message
	extractMsg := &protocol.ExtractMessage{
		Path: path,
	}

	// Encode request
	payload, err := protocol.EncodeExtractMessage(extractMsg)
	if err != nil {
		return fmt.Errorf("failed to encode extract request: %w", err)
	}

	// Send request via protocol
	response, err := ec.client.sendRequest(protocol.EXTRACT, payload)
	if err != nil {
		return fmt.Errorf("failed to send extract request: %w", err)
	}

	// Handle error response
	if response.Type == protocol.ERROR {
		errorMsg, _ := protocol.DecodeErrorMessage(response.Payload)
		return fmt.Errorf("server error %d: %s", errorMsg.Code, errorMsg.Message)
	}

	// Verify response type
	if response.Type != protocol.EXTRACT_RESPONSE {
		return fmt.Errorf("unexpected response type: 0x%02x", response.Type)
	}

	// Decode response
	extractResponse, err := protocol.DecodeExtractResponseMessage(response.Payload)
	if err != nil {
		return fmt.Errorf("failed to decode extract response: %w", err)
	}

	// Check for extraction failure
	if !extractResponse.Success {
		return fmt.Errorf("extraction failed: %s", extractResponse.Error)
	}

	// Generate header comment
	header := ec.generateHeader(pathStr)
	script := header + "\n" + extractResponse.Script

	// Output to file or stdout
	if outputFile != "" {
		err = ec.writeToFile(outputFile, script)
		if err != nil {
			return fmt.Errorf("failed to write to file: %w", err)
		}
		fmt.Printf("✓ MBL script written to %s\n", outputFile)
	} else {
		fmt.Print(script)
	}

	return nil
}

// validatePath validates path components
func (ec *ExtractCommand) validatePath(path []string) error {
	for i, component := range path {
		if component == "" {
			return fmt.Errorf("empty path component at position %d", i)
		}
		// Basic validation for MBL identifier syntax
		if !isValidMBLIdentifier(component) {
			return fmt.Errorf("invalid path component '%s' at position %d", component, i)
		}
	}
	return nil
}

// isValidMBLIdentifier checks if a string is a valid MBL identifier
func isValidMBLIdentifier(s string) bool {
	if len(s) == 0 {
		return false
	}

	// Must start with letter or underscore
	first := s[0]
	if !((first >= 'a' && first <= 'z') || (first >= 'A' && first <= 'Z') || first == '_') {
		return false
	}

	// Remaining characters must be letters, digits, or underscores
	for i := 1; i < len(s); i++ {
		c := s[i]
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
			return false
		}
	}

	return true
}

// generateHeader creates a header comment for the extracted MBL script
func (ec *ExtractCommand) generateHeader(pathStr string) string {
	// Get current timestamp
	timestamp := time.Now().UTC().Format("2006-01-02 15:04:05 UTC")

	// Get node identity from status (if possible)
	nodeIdentity := "unknown"
	if status, err := ec.client.GetStatus(); err == nil {
		nodeIdentity = status.NodeIdentity
	}

	return fmt.Sprintf(`# AmorphDB Data Extract
# Source Path: %s
# Extracted: %s
# Agent: %s
# Generated by: amorphctl extract
#
# This script recreates the current state of the specified subtree.
# Temporal history is not included - only current values are extracted.
#`, pathStr, timestamp, nodeIdentity)
}

// writeToFile writes the script to the specified file
func (ec *ExtractCommand) writeToFile(filename string, script string) error {
	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create file %s: %w", filename, err)
	}
	defer file.Close()

	_, err = file.WriteString(script)
	if err != nil {
		return fmt.Errorf("failed to write to file %s: %w", filename, err)
	}

	return nil
}