#!/bin/bash
# Basic Bridge Setup Workflow
#
# This script demonstrates how to establish a bridge connection
# to a partner mesh and perform basic cross-mesh operations.

set -euo pipefail

# Configuration
PARTNER_ADDRESS="${1:-}"
SOCKET_PATH="${AMORPHDB_SOCKET:-/var/run/amorphdb.sock}"

if [ -z "$PARTNER_ADDRESS" ]; then
    echo "Usage: $0 <partner-mesh-address:port>"
    echo "Example: $0 partner-mesh.example.com:8080"
    exit 1
fi

echo "🌉 Setting up bridge to $PARTNER_ADDRESS..."

# Helper function to run amorphctl commands
adb() {
    amorphctl -s "$SOCKET_PATH" "$@"
}

# Check local node status
echo "📊 Checking local node status..."
LOCAL_STATUS=$(adb status)
echo "$LOCAL_STATUS"

if echo "$LOCAL_STATUS" | grep -q "Status: Standalone"; then
    echo "❌ Error: Local node is standalone. Must be part of a mesh to create bridges."
    echo "   Run: amorphctl create-mesh <mesh-name> first"
    exit 1
fi

# Test network connectivity
echo "🔍 Testing connectivity to partner mesh..."
if ! nc -z "${PARTNER_ADDRESS%:*}" "${PARTNER_ADDRESS#*:}" 2>/dev/null; then
    echo "❌ Error: Cannot connect to $PARTNER_ADDRESS"
    echo "   Check network connectivity and firewall rules"
    exit 1
fi

echo "✅ Network connectivity confirmed"

# Establish bridge connection
echo "🔗 Establishing bridge connection..."
if adb bridge "$PARTNER_ADDRESS"; then
    echo "✅ Bridge established successfully"
else
    echo "❌ Failed to establish bridge"
    echo "Common issues:"
    echo "  - Partner mesh may not allow bridge connections"
    echo "  - Authentication credentials may be missing"
    echo "  - Network firewall blocking connection"
    exit 1
fi

# Wait for bridge to stabilize
echo "⏳ Waiting for bridge to stabilize..."
sleep 3

# Get bridge information
echo "📋 Bridge Information:"
adb bridge list

# Discover partner mesh structure
PARTNER_MESH_NAME=$(adb bridge list | grep "$PARTNER_ADDRESS" | awk '{print $1}')
if [ -z "$PARTNER_MESH_NAME" ]; then
    echo "❌ Could not determine partner mesh name"
    exit 1
fi

echo "🔍 Partner mesh: $PARTNER_MESH_NAME"

# Test basic bridge operations
echo ""
echo "🧪 Testing basic bridge operations..."

# Test 1: Write test data to partner mesh
echo "Test 1: Writing test data to partner mesh"
TEST_PATH="my.$PARTNER_MESH_NAME.test.bridge_setup"
TEST_DATA="Bridge test from $(hostname) at $(date)"

if adb set "$TEST_PATH" "$TEST_DATA"; then
    echo "  ✅ Write successful"
else
    echo "  ❌ Write failed"
    exit 1
fi

# Test 2: Read test data back
echo "Test 2: Reading test data back"
if READ_DATA=$(adb get "$TEST_PATH"); then
    if [ "$READ_DATA" = "$TEST_DATA" ]; then
        echo "  ✅ Read successful - data matches"
    else
        echo "  ⚠️  Read successful but data mismatch:"
        echo "    Expected: $TEST_DATA"
        echo "    Got:      $READ_DATA"
    fi
else
    echo "  ❌ Read failed"
fi

# Test 3: List available data in partner mesh
echo "Test 3: Exploring partner mesh structure"
echo "  Available data paths:"
if adb get "my.$PARTNER_MESH_NAME" 2>/dev/null | head -10; then
    echo "  ✅ Partner mesh exploration successful"
else
    echo "  ⚠️  Limited access to partner mesh data"
fi

# Create bridge monitoring script
cat > "/tmp/bridge_monitor_$PARTNER_MESH_NAME.sh" << EOF
#!/bin/bash
# Bridge monitoring script for $PARTNER_MESH_NAME
# Generated by basic_bridge_setup.sh

echo "Bridge Status for $PARTNER_MESH_NAME:"
echo "=================================="

# Check bridge connection
if amorphctl -s "$SOCKET_PATH" bridge status "$PARTNER_MESH_NAME" 2>/dev/null; then
    echo "✅ Bridge is active"
else
    echo "❌ Bridge connection lost"
    echo ""
    echo "To reconnect:"
    echo "  amorphctl -s $SOCKET_PATH bridge $PARTNER_ADDRESS"
    exit 1
fi

# Test connectivity
echo ""
echo "Testing connectivity..."
if amorphctl -s "$SOCKET_PATH" bridge ping "$PARTNER_MESH_NAME"; then
    echo "✅ Bridge ping successful"
else
    echo "❌ Bridge ping failed"
fi

# Show bridge identity
echo ""
echo "Bridge Identity:"
amorphctl -s "$SOCKET_PATH" bridge identity "$PARTNER_MESH_NAME"

# Test data access
echo ""
echo "Testing data access..."
if amorphctl -s "$SOCKET_PATH" get "$TEST_PATH" >/dev/null 2>&1; then
    echo "✅ Data access working"
else
    echo "❌ Data access failed"
fi

echo ""
echo "Last check: \$(date)"
EOF

chmod +x "/tmp/bridge_monitor_$PARTNER_MESH_NAME.sh"

echo ""
echo "✅ Bridge setup complete!"
echo ""
echo "Bridge Details:"
echo "  Partner mesh: $PARTNER_MESH_NAME"
echo "  Address: $PARTNER_ADDRESS"
echo "  Test path: $TEST_PATH"
echo ""
echo "Next steps:"
echo "  1. Monitor bridge: /tmp/bridge_monitor_$PARTNER_MESH_NAME.sh"
echo "  2. Access partner data: adb get my.$PARTNER_MESH_NAME.path.to.data"
echo "  3. Write to partner: adb set my.$PARTNER_MESH_NAME.your.data 'value'"
echo ""
echo "Useful commands:"
echo "  adb bridge status $PARTNER_MESH_NAME  # Check bridge status"
echo "  adb bridge ping $PARTNER_MESH_NAME    # Test connectivity"
echo "  adb bridge list                       # List all bridges"
echo "  adb detach $PARTNER_MESH_NAME         # Disconnect bridge"